version: '3'

services:

#  frontend:
#    image: frontend-container:v1
#    restart: always
#    networks:
#        - apinetwork
#    expose:
#        - "8100"
#    ports:
#        - "8100:8100"
#    depends_on:
#      - nginx

  jenkins-docker:
    image: docker:dind
    #build: .
    restart: always
    #volumes: ['./api:/api']
    networks:
      - jenkins
    expose:
      - "2376"
    ports:
      - "2376:2376"
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    privileged: true

  jenkins-blueocean:
    image: jenkinsci/blueocean
    restart: always
    networks:
      - jenkins
    expose:
      - "8080"
      - "50000"
    ports:
      - "50000:50000"
      - "8080:8080"
    depends_on:
      - jenkins-docker
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1

networks:
  jenkins: