version: '3'

services:

  mlflowui:
    build: ./mlflowUI/.
    restart: always
    networks:
        - jenkins
    expose:
        - "5000"
    ports:
        - "5000:5000"

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    volumes: ['/volumes/rabbitmq:/var/lib/rabbitmq']
    networks:
      - jenkins
    expose:
      - "5672"
      - "15672"
    ports:
      - "5672:5672"
      - "15672:15672"
    #environment:
    #privileged: true

  jenkins:
    #image: jenkinsci/blueocean
    build: ./jenkins/.
    restart: always
    volumes: ['/var/run/docker.sock:/var/run/docker.sock', '${HOME}/jenkins_home:/var/jenkins_home', '/data/:/data/']
    networks:
      - jenkins
    expose:
      - "8080"
      - "50000"
    ports:
      - "50000:50000"
      - "8080:8080"
    #depends_on:
    #  - jenkins-docker
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1

networks:
  jenkins: