apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflowui
  labels:
    k8s-app: mlflowui
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      k8s-app: mlflowui
  template:
    metadata:
      labels:
        k8s-app: mlflowui
    spec:
      nodeName: raspberrypi1
      containers:
      - image: rio05docker/continuos_learning_ui:latest
        imagePullPolicy: Always
        name: mlflowui
        resources:
            limits:
                memory: "1Gi"
                cpu: "1"
            requests:
                cpu: "100m"
                memory: "30Mi"
        env:
        - name: LANG
          value: C.UTF-8
        - name: LC_ALL
          value: C.UTF-8
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /tmp/mlflowruns/
          name: mlflow-volume
      restartPolicy: Always
      volumes:
      - name: mlflow-volume
        persistentVolumeClaim:
          claimName: mlflow-claim
