artifact_uri: /tmp/mlflowruns/0/bd1e763447ca42baa8c6d66af6e8cff8/artifacts
end_time: 1596732766159
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: bd1e763447ca42baa8c6d66af6e8cff8
run_uuid: bd1e763447ca42baa8c6d66af6e8cff8
source_name: ''
source_type: 4
source_version: ''
start_time: 1596732742373
status: 3
tags: []
user_id: root
